name: deploy

on:
  - push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          cache: npm
          node-version: current
      - run: cd theme
      - run: npm ci
      - run: npm run build

      - uses: JamesIves/github-pages-deploy-action@4.0.0
        if: github.ref == 'refs/heads/master'
        with:
          branch: gh-pages
          folder: ./dist
          single-commit: true
          silent: false
