name: deploy

on:
  - push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        working-directory: theme
        with:
          cache: npm
          node-version: current

      - run: npm ci
        working-directory: theme
      - run: npm run build
        working-directory: theme

      - uses: JamesIves/github-pages-deploy-action@4.0.0
        working-directory: theme
        if: github.ref == 'refs/heads/master'
        with:
          branch: gh-pages
          folder: ./dist
          single-commit: true
          silent: false
